# Generated by Django 2.2.2 on 2019-06-07 07:17
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def populate(apps, schema_editor):
    first_question = add_question(apps, "What's up?", timezone.now())
    second_question = add_question(apps, "What's my name?", timezone.now())
    add_choice(apps, first_question, "Not much")
    add_choice(apps, first_question, "The sky")
    add_choice(apps, second_question, "what?")
    add_choice(apps, second_question, "who?")
    add_choice(apps, second_question, "huh?")
    add_choice(apps, second_question, "Slim Shady")


def add_question(apps, text, publish_date):
    question = apps.get_model("polls", "Question")
    return question.objects.create(
        question_text=text, pub_date=publish_date)


def add_choice(apps, question, choice_text):
    choice = apps.get_model("polls", "Choice")
    return choice.objects.create(
        question=question, choice_text=choice_text)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
        migrations.RunPython(populate)
    ]
